sudo : required
services: 
  - docker
before_install: 
  - docker build -t john.howes/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true john.howes/docker-react npm run test -- --coverage